#!/usr/bin/env bash
# Helper script to bootstrap a new AI agent project following the enterprise workflow.
# Usage: ./create_agent.sh "Agent Name"

set -euo pipefail

action_agent_name="$1"
# Convert to kebab-case for branch and directory names
kebab=$(echo "$action_agent_name" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|[-]+$//g')

# 1. Create a new project directory under projects/
project_dir="projects/$kebab"
mkdir -p "$project_dir"

echo "Created project directory: $project_dir"

# 2. Create a Requirements (epic) issue using the GitHub CLI (if installed)
if command -v gh >/dev/null 2>&1; then
  gh issue create \
    --title "$action_agent_name Requirements" \
    --label "epic" \
    --body "$(cat .github/ISSUE_TEMPLATE/agent_requirements.md)"
else
  echo "GitHub CLI (gh) not installed – please create the requirements issue manually using the template at .github/ISSUE_TEMPLATE/agent_requirements.md"
fi

# 3. Create a git branch for the feature
git checkout -b "feat/$kebab"

echo "Switched to branch feat/$kebab"

# 4. Open a draft Pull Request (if gh is available)
if command -v gh >/dev/null 2>&1; then
  gh pr create --title "feat($kebab): initial skeleton for $action_agent_name" \
    --body "Initial skeleton autogenerated by create_agent.sh. Please add implementation, tests, and documentation." \
    --draft
else
  echo "GitHub CLI (gh) not installed – push the branch and open a PR manually."
fi

echo "Done."
